micronaut:
  application:
    name: demo
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

jpa:
  default:
    entity-scan:
      packages: 'com.example'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true