micronaut:
  application:
    name: demo
  server:
    port: 8085
    maxRequestSize: 1MB
  router:
    versioning:
      enabled: true
      default-version: 1.1
      parameter:
        enabled: false
        names: 'v,api-version'
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: 'jdbc:h2:mem:liquibaseDisabledDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'

jpa:
  default:
    entity-scan:
      packages: 'com.example.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'